[package]
name = "smartschool"
version = "0.1.0"
authors = ["Bas De Bue <bas.de.bue@edpnet.be>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/basdebue/smartschool"
description = "Smartschool client library for Rust."
categories = ["api-bindings"]
keywords = ["api", "smartschool"]
edition = "2018"

[dependencies]
regex = "1.1.6"
reqwest = "0.9.15"

[dependencies.futures-01]
package = "futures"
version = "0.1.23"

[dependencies.futures-preview]
version = "0.3.0-alpha.14"
features = ["compat"]